### ISSUE TITLE
ValueError: Plugin xrootd supports tagged values but specifies args with multiple values in its settings class.

### ISSUE THREAD

**Issue by veprbl** [snakemake/snakemake-storage-plugin-xrootd#2]
```
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/snakemake/cli.py", line 2054, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/snakemake/cli.py", line 1643, in parse_args
    parser = get_argument_parser()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/snakemake/cli.py", line 1626, in get_argument_parser
    StoragePluginRegistry().register_cli_args(parser)
  File "/lib/python3.11/site-packages/snakemake_interface_common/plugin_registry/__init__.py", line 60, in register_cli_args
    plugin.register_cli_args(argparser)
  File "/lib/python3.11/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 147, in register_cli_args
    raise ValueError(
ValueError: Plugin xrootd supports tagged values but specifies args with multiple values in its settings class. This is not supported and a bug in the plugin. Please file an issue in the plugin repository.
```

**Comment by johanneskoester** [comment]
I think this is fixed with the release 3 weeks ago. Please feel free to reopen in case I am wrong.
